briefs_dir = "_story_briefs"
brief_file_pattern = "*cs*.md"
required_dir = "briefs_dir"
required_dir = "_condamad"
required_dir = "_condamad\stories"
required_dir = ".agents"

current_dir = "C:\dev\horoscope_front"
