"""Catalogue statique des profils symboliques de conditions avancees."""

from __future__ import annotations

from app.domain.astrology.interpretation.advanced_conditions.contracts import (
    AdvancedConditionInterpretationProfile,
    InterpretationIntensity,
    InterpretationPolarity,
)


def _profile(
    condition_key: str,
    polarity: InterpretationPolarity,
    intensity: InterpretationIntensity,
    *,
    keywords: tuple[str, ...],
    themes: tuple[str, ...],
    manifestations: tuple[str, ...],
    psychological_axes: tuple[str, ...],
    behavioral_axes: tuple[str, ...],
    notes: tuple[str, ...] = (),
    planet_key: str | None = None,
    tradition_key: str | None = None,
) -> AdvancedConditionInterpretationProfile:
    """Construit une entree courte du catalogue canonique."""
    return AdvancedConditionInterpretationProfile(
        condition_key=condition_key,
        planet_key=planet_key,
        tradition_key=tradition_key,
        polarity=polarity,
        intensity=intensity,
        keywords=keywords,
        themes=themes,
        manifestations=manifestations,
        psychological_axes=psychological_axes,
        behavioral_axes=behavioral_axes,
        notes=notes,
    )


ADVANCED_CONDITION_PROFILE_CATALOG: tuple[AdvancedConditionInterpretationProfile, ...] = (
    _profile(
        "combust",
        InterpretationPolarity.NEGATIVE,
        InterpretationIntensity.HIGH,
        keywords=("hidden", "burned", "overpowered"),
        themes=("solar domination", "reduced autonomy"),
        manifestations=("low visibility", "absorbed function"),
        psychological_axes=("pressure", "identification"),
        behavioral_axes=("restraint", "indirect expression"),
    ),
    _profile(
        "combust",
        InterpretationPolarity.MIXED,
        InterpretationIntensity.HIGH,
        keywords=("sharp mind", "nervous heat", "compressed speech"),
        themes=("mental concentration", "solarized exchange"),
        manifestations=("fast associations", "private reasoning"),
        psychological_axes=("focus", "overload"),
        behavioral_axes=("selective wording", "urgent analysis"),
        planet_key="mercury",
    ),
    _profile(
        "combust",
        InterpretationPolarity.MIXED,
        InterpretationIntensity.HIGH,
        keywords=("sealed message", "courtly caution", "heated craft"),
        themes=("solar witness", "guarded mediation"),
        manifestations=("coded exchange", "compressed argument"),
        psychological_axes=("prudence", "intensity"),
        behavioral_axes=("careful speech", "tactical silence"),
        planet_key="mercury",
        tradition_key="medieval",
    ),
    _profile(
        "cazimi",
        InterpretationPolarity.POSITIVE,
        InterpretationIntensity.EXTREME,
        keywords=("empowered", "protected", "purified"),
        themes=("solar protection", "central clarity"),
        manifestations=("direct access", "heightened presence"),
        psychological_axes=("confidence", "alignment"),
        behavioral_axes=("decisive expression", "visible agency"),
    ),
    _profile(
        "retrograde",
        InterpretationPolarity.MIXED,
        InterpretationIntensity.MODERATE,
        keywords=("internalized", "revisiting", "reprocessing"),
        themes=("return movement", "inner revision"),
        manifestations=("delayed expression", "recursive attention"),
        psychological_axes=("reflection", "self-questioning"),
        behavioral_axes=("review", "iteration"),
    ),
    _profile(
        "retrograde",
        InterpretationPolarity.NEUTRAL,
        InterpretationIntensity.MODERATE,
        keywords=("traditional review", "recovered thread", "deliberation"),
        themes=("inherited method", "temporal return"),
        manifestations=("measured pace", "archival attention"),
        psychological_axes=("memory", "discernment"),
        behavioral_axes=("reassessment", "patient correction"),
        tradition_key="medieval",
    ),
    _profile(
        "stationary",
        InterpretationPolarity.MIXED,
        InterpretationIntensity.HIGH,
        keywords=("amplified", "concentrated", "blocked momentum"),
        themes=("threshold motion", "fixed attention"),
        manifestations=("intensified pause", "directional pivot"),
        psychological_axes=("suspension", "readiness"),
        behavioral_axes=("waiting", "decisive shift"),
    ),
    _profile(
        "under_beams",
        InterpretationPolarity.NEGATIVE,
        InterpretationIntensity.MODERATE,
        keywords=("obscured", "subtle", "covered"),
        themes=("solar concealment", "limited exposure"),
        manifestations=("partial access", "muted signal"),
        psychological_axes=("reserve", "protection"),
        behavioral_axes=("caution", "indirect timing"),
    ),
    _profile(
        "invisible",
        InterpretationPolarity.NEGATIVE,
        InterpretationIntensity.HIGH,
        keywords=("unseen", "withdrawn", "latent"),
        themes=("hidden agency", "submerged function"),
        manifestations=("low recognition", "private operation"),
        psychological_axes=("secrecy", "containment"),
        behavioral_axes=("retreat", "behind-scenes action"),
    ),
    _profile(
        "emerging",
        InterpretationPolarity.POSITIVE,
        InterpretationIntensity.MODERATE,
        keywords=("reappearing", "awakening", "returning visibility"),
        themes=("return to view", "fresh agency"),
        manifestations=("growing visibility", "new signal"),
        psychological_axes=("confidence", "awakening"),
        behavioral_axes=("announcement", "first initiative"),
    ),
    _profile(
        "oriental",
        InterpretationPolarity.POSITIVE,
        InterpretationIntensity.LOW,
        keywords=("morning", "initiating", "forward"),
        themes=("earlier emergence", "active stance"),
        manifestations=("quick response", "first movement"),
        psychological_axes=("anticipation", "initiative"),
        behavioral_axes=("starting", "leading"),
    ),
    _profile(
        "occidental",
        InterpretationPolarity.NEUTRAL,
        InterpretationIntensity.LOW,
        keywords=("evening", "receiving", "settling"),
        themes=("later visibility", "responsive stance"),
        manifestations=("delayed response", "assimilated movement"),
        psychological_axes=("integration", "evaluation"),
        behavioral_axes=("responding", "consolidating"),
    ),
    _profile(
        "full_moon",
        InterpretationPolarity.MIXED,
        InterpretationIntensity.HIGH,
        keywords=("culmination", "awareness", "illumination"),
        themes=("lunar fullness", "opposition of lights"),
        manifestations=("heightened contrast", "visible feeling"),
        psychological_axes=("awareness", "tension"),
        behavioral_axes=("exposure", "completion"),
    ),
    _profile(
        "new_moon",
        InterpretationPolarity.NEUTRAL,
        InterpretationIntensity.MODERATE,
        keywords=("seed", "beginning", "internalization"),
        themes=("lunar renewal", "hidden inception"),
        manifestations=("low external signal", "fresh imprint"),
        psychological_axes=("potential", "interiority"),
        behavioral_axes=("starting quietly", "gestating"),
    ),
)
