# Conventions partagees de longueurs SQLAlchemy pour les modeles LLM.
"""Centralise les longueurs des concepts texte communs au perimetre LLM."""

from __future__ import annotations

FEATURE_LENGTH = 64
SUBFEATURE_LENGTH = 64
PLAN_LENGTH = 64
LOCALE_LENGTH = 32
PROVIDER_LENGTH = 32
MODEL_LENGTH = 100
VERSION_LENGTH = 64
REQUEST_ID_LENGTH = 100
TRACE_ID_LENGTH = 100
USE_CASE_LENGTH = 100
PIPELINE_KIND_LENGTH = 32
EXECUTION_PATH_KIND_LENGTH = 40
FALLBACK_KIND_LENGTH = 40
CONTEXT_QUALITY_LENGTH = 32
ERROR_CODE_LENGTH = 80
SHORT_STATUS_LENGTH = 20
MANIFEST_ENTRY_ID_LENGTH = 100
