"""create_llm_prompt_registry_tables

Revision ID: 0be022f23e03
Revises: 20260226_0027
Create Date: 2026-03-01 11:30:05.012092
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be022f23e03'
down_revision: Union[str, Sequence[str], None] = '20260226_0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_use_case_configs',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('output_schema_id', sa.String(length=64), nullable=True),
    sa.Column('allowed_persona_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('llm_prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('use_case_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('developer_prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('fallback_use_case_key', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['use_case_key'], ['llm_use_case_configs.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_prompt_version_active_unique', 'llm_prompt_versions', ['use_case_key'], unique=True, postgresql_where=sa.text("status = 'published'"), sqlite_where=sa.text("status = 'published'"))
    op.create_index(op.f('ix_llm_prompt_versions_status'), 'llm_prompt_versions', ['status'], unique=False)
    op.create_index(op.f('ix_llm_prompt_versions_use_case_key'), 'llm_prompt_versions', ['use_case_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_prompt_versions_use_case_key'), table_name='llm_prompt_versions')
    op.drop_index(op.f('ix_llm_prompt_versions_status'), table_name='llm_prompt_versions')
    op.drop_index('ix_llm_prompt_version_active_unique', table_name='llm_prompt_versions', postgresql_where=sa.text("status = 'published'"), sqlite_where=sa.text("status = 'published'"))
    op.drop_table('llm_prompt_versions')
    op.drop_table('llm_use_case_configs')
    # ### end Alembic commands ###
