"""extend_use_case_config_contract

Revision ID: 12216bc815ed
Revises: 2b616cdc516a
Create Date: 2026-03-01 13:33:09.103413
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12216bc815ed"
down_revision: Union[str, Sequence[str], None] = "2b616cdc516a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("llm_use_case_configs", sa.Column("input_schema", sa.JSON(), nullable=True))
    op.add_column(
        "llm_use_case_configs",
        sa.Column("required_prompt_placeholders", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_use_case_configs", "required_prompt_placeholders")
    op.drop_column("llm_use_case_configs", "input_schema")
    # ### end Alembic commands ###
