"""add_execution_profile_ref_to_assembly

Revision ID: 21011e7e01f2
Revises: cc211a38294d
Create Date: 2026-04-08 15:48:12.178316
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21011e7e01f2"
down_revision: Union[str, Sequence[str], None] = "cc211a38294d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_assembly_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("execution_profile_ref", sa.UUID(), nullable=True))
        batch_op.create_foreign_key(
            "fk_llm_assembly_configs_execution_profile_ref",
            "llm_execution_profiles",
            ["execution_profile_ref"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_assembly_configs", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_llm_assembly_configs_execution_profile_ref", type_="foreignkey"
        )
        batch_op.drop_column("execution_profile_ref")
    # ### end Alembic commands ###
