"""add_fallback_to_use_case_config

Revision ID: 2b616cdc516a
Revises: afe029f0f78d
Create Date: 2026-03-01 13:09:24.569379
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b616cdc516a"
down_revision: Union[str, Sequence[str], None] = "afe029f0f78d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "llm_use_case_configs",
        sa.Column("fallback_use_case_key", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_use_case_configs", "fallback_use_case_key")
    # ### end Alembic commands ###
