"""add_product_entitlements_tables

Revision ID: 3d0bd31c3b51
Revises: 20260324_0053
Create Date: 2026-03-25 15:35:38.705460
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3d0bd31c3b51'
down_revision: Union[str, Sequence[str], None] = '20260324_0053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_code', sa.String(length=64), nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_metered', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_catalog_feature_code'), ['feature_code'], unique=True)

    op.create_table('plan_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('audience', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_catalog_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_catalog_plan_code'), ['plan_code'], unique=True)

    op.create_table('feature_usage_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_code', sa.String(length=64), nullable=False),
    sa.Column('quota_key', sa.String(length=64), nullable=False),
    sa.Column('period_unit', sa.String(length=32), nullable=False),
    sa.Column('period_value', sa.Integer(), nullable=False),
    sa.Column('reset_mode', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('used_count >= 0', name='ck_feature_usage_counters_used_count_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_code', 'quota_key', 'period_unit', 'period_value', 'reset_mode', 'window_start', name='uq_feature_usage_counters_composite')
    )
    with op.batch_alter_table('feature_usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_usage_counters_feature_code'), ['feature_code'], unique=False)
        batch_op.create_index('ix_feature_usage_counters_user_feature', ['user_id', 'feature_code'], unique=False)
        batch_op.create_index('ix_feature_usage_counters_user_feature_quota', ['user_id', 'feature_code', 'quota_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_usage_counters_user_id'), ['user_id'], unique=False)

    op.create_table('plan_feature_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('access_mode', sa.String(length=32), nullable=False),
    sa.Column('variant_code', sa.String(length=64), nullable=True),
    sa.Column('source_origin', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_id', name='uq_plan_feature_bindings_plan_feature')
    )
    with op.batch_alter_table('plan_feature_bindings', schema=None) as batch_op:
        batch_op.create_index('ix_plan_feature_bindings_feature_id', ['feature_id'], unique=False)
        batch_op.create_index('ix_plan_feature_bindings_plan_id', ['plan_id'], unique=False)

    op.create_table('plan_feature_quotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_feature_binding_id', sa.Integer(), nullable=False),
    sa.Column('quota_key', sa.String(length=64), nullable=False),
    sa.Column('quota_limit', sa.Integer(), nullable=False),
    sa.Column('period_unit', sa.String(length=32), nullable=False),
    sa.Column('period_value', sa.Integer(), nullable=False),
    sa.Column('reset_mode', sa.String(length=32), nullable=False),
    sa.Column('source_origin', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_value >= 1', name='ck_plan_feature_quotas_period_value_positive'),
    sa.CheckConstraint('quota_limit > 0', name='ck_plan_feature_quotas_quota_limit_positive'),
    sa.ForeignKeyConstraint(['plan_feature_binding_id'], ['plan_feature_bindings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_feature_binding_id', 'quota_key', 'period_unit', 'period_value', 'reset_mode', name='uq_plan_feature_quotas_composite')
    )
    with op.batch_alter_table('plan_feature_quotas', schema=None) as batch_op:
        batch_op.create_index('ix_plan_feature_quotas_binding_id', ['plan_feature_binding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_feature_quotas', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_feature_quotas_binding_id')

    op.drop_table('plan_feature_quotas')
    with op.batch_alter_table('plan_feature_bindings', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_feature_bindings_plan_id')
        batch_op.drop_index('ix_plan_feature_bindings_feature_id')

    op.drop_table('plan_feature_bindings')
    with op.batch_alter_table('feature_usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_usage_counters_user_id'))
        batch_op.drop_index('ix_feature_usage_counters_user_feature_quota')
        batch_op.drop_index('ix_feature_usage_counters_user_feature')
        batch_op.drop_index(batch_op.f('ix_feature_usage_counters_feature_code'))

    op.drop_table('feature_usage_counters')
    with op.batch_alter_table('plan_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_catalog_plan_code'))
        batch_op.drop_index(batch_op.f('ix_plan_catalog_audience'))

    op.drop_table('plan_catalog')
    with op.batch_alter_table('feature_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_catalog_feature_code'))

    op.drop_table('feature_catalog')
    # ### end Alembic commands ###
