"""add_llm_persona_model

Revision ID: 4665be3c5a76
Revises: 0be022f23e03
Create Date: 2026-03-01 12:19:34.058267
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4665be3c5a76"
down_revision: Union[str, Sequence[str], None] = "0be022f23e03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_personas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tone", sa.String(length=32), nullable=False),
        sa.Column("verbosity", sa.String(length=32), nullable=False),
        sa.Column("style_markers", sa.JSON(), nullable=False),
        sa.Column("boundaries", sa.JSON(), nullable=False),
        sa.Column("allowed_topics", sa.JSON(), nullable=False),
        sa.Column("disallowed_topics", sa.JSON(), nullable=False),
        sa.Column("formatting", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_personas")
    # ### end Alembic commands ###
