"""add_safety_profile_to_use_case

Revision ID: 577048f1686f
Revises: caf87c3d461f
Create Date: 2026-03-01 13:05:00.316886
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577048f1686f'
down_revision: Union[str, Sequence[str], None] = 'caf87c3d461f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_use_case_configs', sa.Column('safety_profile', sa.String(length=32), nullable=False, server_default='astrology'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_use_case_configs', 'safety_profile')
    # ### end Alembic commands ###
