"""add_length_budget_to_assembly

Revision ID: 5e52f7244424
Revises: 21011e7e01f2
Create Date: 2026-04-08 15:53:12.178316
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e52f7244424'
down_revision: Union[str, Sequence[str], None] = '21011e7e01f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_assembly_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_budget', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_assembly_configs', schema=None) as batch_op:
        batch_op.drop_column('length_budget')
    # ### end Alembic commands ###
