"""Add scheduled plan and period start fields to stripe billing profile

Revision ID: 63ea7085e863
Revises: 20260329_0064
Create Date: 2026-03-31 10:15:21.435437
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ea7085e863'
down_revision: Union[str, Sequence[str], None] = '20260329_0064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_billing_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scheduled_plan_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('scheduled_change_effective_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pending_cancellation_effective_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_billing_profiles', schema=None) as batch_op:
        batch_op.drop_column('pending_cancellation_effective_at')
        batch_op.drop_column('scheduled_change_effective_at')
        batch_op.drop_column('scheduled_plan_code')
        batch_op.drop_column('current_period_start')
    # ### end Alembic commands ###
