"""add_consultation_templates

Revision ID: 7507b4a98306
Revises: 20260323_1120
Create Date: 2026-03-23 13:46:45.496155
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7507b4a98306'
down_revision: Union[str, Sequence[str], None] = '20260323_1120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('icon_ref', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('metadata_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_templates', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_consultation_templates_is_active'),
            ['is_active'],
            unique=False
        )
        batch_op.create_index(batch_op.f('ix_consultation_templates_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_templates_key'))
        batch_op.drop_index(batch_op.f('ix_consultation_templates_is_active'))

    op.drop_table('consultation_templates')
    # ### end Alembic commands ###
