"""create_llm_output_schemas_table

Revision ID: afe029f0f78d
Revises: 577048f1686f
Create Date: 2026-03-01 13:05:32.978854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe029f0f78d'
down_revision: Union[str, Sequence[str], None] = '577048f1686f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_output_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('json_schema', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_output_schemas_name'), 'llm_output_schemas', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_output_schemas_name'), table_name='llm_output_schemas')
    op.drop_table('llm_output_schemas')
    # ### end Alembic commands ###
