"""add_v3_persistence_fields

Revision ID: b8bebaa43652
Revises: 20260311_0045
Create Date: 2026-03-11 17:51:18.811204
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bebaa43652'
down_revision: Union[str, Sequence[str], None] = '20260311_0045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_prediction_category_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_day', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dominance_day', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stability_day', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('intensity_day', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_score', sa.Float(), nullable=True))

    with op.batch_alter_table('daily_prediction_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('v3_metrics_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_prediction_runs', schema=None) as batch_op:
        batch_op.drop_column('v3_metrics_json')

    with op.batch_alter_table('daily_prediction_category_scores', schema=None) as batch_op:
        batch_op.drop_column('min_score')
        batch_op.drop_column('max_score')
        batch_op.drop_column('avg_score')
        batch_op.drop_column('intensity_day')
        batch_op.drop_column('stability_day')
        batch_op.drop_column('dominance_day')
        batch_op.drop_column('level_day')
    # ### end Alembic commands ###
