"""add_persona_strategy_to_use_case

Revision ID: caf87c3d461f
Revises: 4665be3c5a76
Create Date: 2026-03-01 12:22:05.494328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf87c3d461f'
down_revision: Union[str, Sequence[str], None] = '4665be3c5a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_use_case_configs', sa.Column('persona_strategy', sa.String(length=16), nullable=False, server_default='optional'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_use_case_configs', 'persona_strategy')
    # ### end Alembic commands ###
