"""add_llm_execution_profiles

Revision ID: cc211a38294d
Revises: 20260408_0068
Create Date: 2026-04-08 15:43:12.178316
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc211a38294d"
down_revision: Union[str, Sequence[str], None] = "20260408_0068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_execution_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("reasoning_profile", sa.String(length=20), nullable=False),
        sa.Column("verbosity_profile", sa.String(length=20), nullable=False),
        sa.Column("output_mode", sa.String(length=20), nullable=False),
        sa.Column("tool_mode", sa.String(length=20), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("fallback_profile_id", sa.UUID(), nullable=True),
        sa.Column("feature", sa.String(length=100), nullable=True),
        sa.Column("subfeature", sa.String(length=100), nullable=True),
        sa.Column("plan", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fallback_profile_id"],
            ["llm_execution_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_execution_profiles", schema=None) as batch_op:
        batch_op.create_index("ix_llm_execution_profiles_feature", ["feature"], unique=False)
        batch_op.create_index("ix_llm_execution_profiles_status", ["status"], unique=False)
        # Note: ix_llm_execution_profile_active_unique is expression-based and usually manually added
        # but for SQLite/Alembic we can try simple columns or just rely on SQLAlchemy create_all for local dev
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_execution_profiles")
    # ### end Alembic commands ###
