"""add is_suspended and is_locked to users

Revision ID: ce173983d275
Revises: 2964d54e4131
Create Date: 2026-04-05 22:48:45.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce173983d275"
down_revision: Union[str, None] = "2964d54e4131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_suspended", sa.Boolean(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "users", sa.Column("is_locked", sa.Boolean(), nullable=False, server_default=sa.text("0"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_locked")
    op.drop_column("users", "is_suspended")
    # ### end Alembic commands ###
