"""add user token usage logs

Revision ID: d86bb999566a
Revises: 63ea7085e863
Create Date: 2026-04-01 11:14:44.612868
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86bb999566a'
down_revision: Union[str, Sequence[str], None] = '63ea7085e863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token_usage_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('feature_code', sa.String(length=100), nullable=False),
        sa.Column('provider_model', sa.String(length=100), nullable=False),
        sa.Column('tokens_in', sa.Integer(), nullable=False),
        sa.Column('tokens_out', sa.Integer(), nullable=False),
        sa.Column('tokens_total', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.String(length=100), nullable=False),
        sa.Column('llm_call_log_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['llm_call_log_id'], ['llm_call_logs.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('tokens_total = tokens_in + tokens_out', name='check_tokens_total_consistency'),
        sa.CheckConstraint('tokens_in >= 0', name='check_tokens_in_positive'),
        sa.CheckConstraint('tokens_out >= 0', name='check_tokens_out_positive')
    )
    with op.batch_alter_table('user_token_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_token_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_token_usage_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_token_usage_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_token_usage_logs_user_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_user_token_usage_logs_user_feature_created_at', ['user_id', 'feature_code', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token_usage_logs_user_feature_created_at')
        batch_op.drop_index('ix_user_token_usage_logs_user_created_at')
        batch_op.drop_index(batch_op.f('ix_user_token_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_token_usage_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_user_token_usage_logs_created_at'))

    op.drop_table('user_token_usage_logs')
    # ### end Alembic commands ###
