"""add_consultation_third_party_tables

Revision ID: f1274b6a70ac
Revises: 7507b4a98306
Create Date: 2026-03-23 21:52:31.212484
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1274b6a70ac'
down_revision: Union[str, Sequence[str], None] = '7507b4a98306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_third_party_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.String(length=8), nullable=True),
    sa.Column('birth_time_known', sa.Boolean(), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('birth_timezone', sa.String(length=64), nullable=False),
    sa.Column('birth_city', sa.String(length=255), nullable=True),
    sa.Column('birth_country', sa.String(length=100), nullable=True),
    sa.Column('birth_lat', sa.Float(), nullable=True),
    sa.Column('birth_lon', sa.Float(), nullable=True),
    sa.Column('birth_place_resolved_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['birth_place_resolved_id'], ['geo_place_resolved.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_third_party_profiles', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_consultation_third_party_profiles_birth_place_resolved_id'),
            ['birth_place_resolved_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_consultation_third_party_profiles_external_id'),
            ['external_id'],
            unique=True
        )
        batch_op.create_index(
            batch_op.f('ix_consultation_third_party_profiles_user_id'),
            ['user_id'],
            unique=False
        )

    op.create_table('consultation_third_party_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('third_party_profile_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.String(length=100), nullable=False),
    sa.Column('consultation_type', sa.String(length=50), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['third_party_profile_id'], ['consultation_third_party_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_third_party_usages', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_consultation_third_party_usages_consultation_id'),
            ['consultation_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_consultation_third_party_usages_third_party_profile_id'),
            ['third_party_profile_id'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('consultation_third_party_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_third_party_usages_third_party_profile_id'))
        batch_op.drop_index(batch_op.f('ix_consultation_third_party_usages_consultation_id'))

    op.drop_table('consultation_third_party_usages')
    with op.batch_alter_table('consultation_third_party_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_third_party_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_consultation_third_party_profiles_external_id'))
        batch_op.drop_index(batch_op.f('ix_consultation_third_party_profiles_birth_place_resolved_id'))

    op.drop_table('consultation_third_party_profiles')
    # ### end Alembic commands ###
