"""add_astrologer_details_and_reviews

Revision ID: f44760fae191
Revises: 20260322_0052
Create Date: 2026-03-22 22:37:14.068636
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f44760fae191'
down_revision: Union[str, Sequence[str], None] = '20260322_0052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astrologer_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['llm_personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('astrologer_reviews', schema=None) as batch_op:
        batch_op.create_index(
            'ix_astrologer_review_user_persona', ['user_id', 'persona_id'], unique=True
        )
        batch_op.create_index(
            batch_op.f('ix_astrologer_reviews_persona_id'), ['persona_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_astrologer_reviews_user_id'), ['user_id'], unique=False
        )

    with op.batch_alter_table('astrologer_profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('specialties_details', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('quote', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mission_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ideal_for', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('astrologer_profiles', schema=None) as batch_op:
        batch_op.drop_column('metrics')
        batch_op.drop_column('ideal_for')
        batch_op.drop_column('mission_statement')
        batch_op.drop_column('quote')
        batch_op.drop_column('location')
        batch_op.drop_column('specialties_details')

    with op.batch_alter_table('astrologer_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_astrologer_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_astrologer_reviews_persona_id'))
        batch_op.drop_index('ix_astrologer_review_user_persona')

    op.drop_table('astrologer_reviews')
    # ### end Alembic commands ###
