"""complete_v3_persistence_fields

Revision ID: fbdf4f0c6837
Revises: b8bebaa43652
Create Date: 2026-03-11 17:59:31.422573

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fbdf4f0c6837"
down_revision: Union[str, Sequence[str], None] = "b8bebaa43652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration was intended to ensure all v3 persistence fields are present.
    # Autogeneration detected unrelated UUID changes that were breaking on SQLite.
    # Since the relevant tables are already in sync with the models, this migration is empty.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
