"""add_pdf_templates_and_interpretation_listing_index

Revision ID: fd1d41d35808
Revises: 20260304_0028
Create Date: 2026-03-04 20:21:39.917728
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd1d41d35808"
down_revision: Union[str, Sequence[str], None] = "20260304_0028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "DRAFT", name="pdftemplatestatus"),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pdf_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pdf_templates_is_default"), ["is_default"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pdf_templates_key"), ["key"], unique=True)
        batch_op.create_index(batch_op.f("ix_pdf_templates_locale"), ["locale"], unique=False)
        batch_op.create_index(batch_op.f("ix_pdf_templates_status"), ["status"], unique=False)

    if inspector.has_table("user_natal_interpretations"):
        with op.batch_alter_table("user_natal_interpretations", schema=None) as batch_op:
            batch_op.create_index(
                "idx_user_natal_interpretations_listing",
                ["user_id", "chart_id", "level", "created_at"],
                unique=False,
            )

    # Seed default template
    op.execute(
        "INSERT INTO pdf_templates (key, name, description, locale, status, version, "
        "config_json, is_default, created_at, updated_at) "
        "VALUES ('default_natal', 'Template Natal Standard', "
        "'Modèle par défaut pour les interprétations natales', 'fr', 'ACTIVE', '1.0.0', "
        "'{}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    if inspector.has_table("user_natal_interpretations"):
        with op.batch_alter_table("user_natal_interpretations", schema=None) as batch_op:
            batch_op.drop_index("idx_user_natal_interpretations_listing")

    with op.batch_alter_table("pdf_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pdf_templates_status"))
        batch_op.drop_index(batch_op.f("ix_pdf_templates_locale"))
        batch_op.drop_index(batch_op.f("ix_pdf_templates_key"))
        batch_op.drop_index(batch_op.f("ix_pdf_templates_is_default"))

    op.drop_table("pdf_templates")
    # ### end Alembic commands ###
